org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError -Djavax.net.ssl.trustStoreType=Windows-ROOT
android.useAndroidX=true
# O caminho do projeto tem acentos (Programação/Móveis), o que trava o
# Android Gradle Plugin por padrão. Ver http://b.android.com/95744
android.overridePathCheck=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
