// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo-ZipRwdt_SNmuh23VEwoXUb6a2tyCWw',
    appId: '1:998317916069:web:52fcfc58f27e613197724c',
    messagingSenderId: '998317916069',
    projectId: 'petvida-petdisp2026',
    authDomain: 'petvida-petdisp2026.firebaseapp.com',
    storageBucket: 'petvida-petdisp2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_Y2ZTYxERE7cpTwfGhJU4iMXc5_IdovI',
    appId: '1:998317916069:android:d395ba2cd816a48297724c',
    messagingSenderId: '998317916069',
    projectId: 'petvida-petdisp2026',
    storageBucket: 'petvida-petdisp2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZLhxb2WyycTioVkJjqu4iEIV2J7DPsyk',
    appId: '1:998317916069:ios:cec52415a9801d5c97724c',
    messagingSenderId: '998317916069',
    projectId: 'petvida-petdisp2026',
    storageBucket: 'petvida-petdisp2026.firebasestorage.app',
    iosBundleId: 'com.petvida.petvida',
  );
}
